from pathlib import Path
import json
H=Path(__file__).resolve().parent
v=json.loads((H/'verification.json').read_text(encoding='utf-8'));r=json.loads((H/'result.json').read_text(encoding='utf-8'));a=json.loads((H/'pipeline_audit.json').read_text(encoding='utf-8'));replay=json.loads((H/'replay_verification.json').read_text(encoding='utf-8'))
assert v['status']==a['status']==replay['status']=='PASS' and all(q=='REJECT' for q in v['verdicts'].values())
desc={'A1':'학습: 내부OOF 물리잔차','B1':'계산: 공기추종 Ridge prior','C1':'피처: 현재 대비 이력 온도차6열','I1':'추론: 내부OOF 잔차계수 학습'}
lines=['# 온도 학습·계산·피처·추론 개선4안 · 2026-10-03','', '사용자 요청의 네 영역을 원 CODEX 구성원에 각각 적용해 별도로 비교했다. 새 후보를 섞거나 기존 W30G 비중을 바꾸지 않았다. 네 안 모두 채택 기준 불통과로 기존 W30G 유지.','', '## 구현','', '- A1: 원 in-sample 물리 잔차 대신 외부 학습일 내부3fold physics OOF를 빼서 잔차 트리 학습. 각 내부fold도 같은 온실 인접 ±1일을 제외. 외부query 정답은 물리/트리/계수 적합에서 전부 제외.','- B1: y 대신 y−in_temp_reset3를 원19열 Ridge100으로 적합하고 그 입력 anchor를 다시 더함. 선형 함수 공간은 원래와 같지만 Ridge 정규화가 온도 기울기를0으로 당기는 대신 공기추종값으로 당기는 계산 변경이다. 모델의 공기추종 prior가 적합하다는 가설만 시험하며 물리 법칙 확정 주장은 아니다.','- C1: 원89열 유지, in_temp_h0/mean/reset1/3/8−현재in_temp와 reset3−reset8 총6열 추가. 물리식·잔차타깃·모델 설정은 동일. 새 정보원을 만든 것이 아니라 기존 입력의 상대적 표현을 트리가 직접 사용하도록 바꾼다.','- I1: 같은 내부3fold의 원 physics/LGB OOF에서 잔차 계수 gamma를 학습한다. gamma=clip((Σw*r*(y−physics)+100)/(Σw*r²+100),0,1.25). 추론은 physics+gamma*residual. 고정100은1에대한정규화. 출력평활이 아니며 외부검증정답으로 계수를 고르지 않았다.','', '## 원 W30G 대비 결과','', 'DIAG10 400일/9,600행, EXT10 85일/2,040행, EXT12 219일/5,256행. 후보당2시드×2PFN문맥×3검증기12칸. 양수는 RMSE악화.','', '| 안 | DIAG10 변화 | EXT10 변화 | EXT12 변화 | 개선 칸 | DIAG p_worse |','|---|---:|---:|---:|---:|---:|']
for tag in desc:
    ss=[s for s in v['cells'] if s['member']==tag];parts=[]
    for val in ['DIAG10','EXT10','EXT12']:
        q=[s['delta_pct'] for s in ss if s['validator']==val];parts.append(f'{min(q):+.3f}~{max(q):+.3f}%')
    ps=[s['p_worse'] for s in ss if s['validator']=='DIAG10'];lines.append(f'| {tag} {desc[tag]} | '+' | '.join(parts)+f' | {sum(s["delta_pct"]<0 for s in ss)}/12 | {min(ps):.5f}~{max(ps):.5f} |')
lines+=['', 'B1은 저온 두 검증에서 개선했으나 일반검증에서 악화. C1은 DIAG/EXT10만 개선하고 EXT12 악화. A1은 EXT12만 개선, I1은 DIAG만 개선. 사전 main eb84db8 기준(전12칸개선 및DIAG p<.025/15·99.666667% ΔMSE CI상한<0)은전부실패. 보정없는.025에서도모두실패하므로본페로니때문에만기각한것이아니다. 이 네 고정 적용안 불통과 판정 신뢰도 높음. 다른 계산법/피처/학습법 전체 불가능성은 판단하지 않는다.','', '## 학습·검증 격차와 오차 위치','']
for tag in desc:
    st=[s['scores'][tag] for s in r['training_scores'] if s['validator']=='DIAG10'];lines.append(f'- {tag} CODEX구성원 fold 학습RMSE {min(s["train_rmse"] for s in st):.4f}~{max(s["train_rmse"] for s in st):.4f}, 검증 {min(s["validation_rmse"] for s in st):.4f}~{max(s["validation_rmse"] for s in st):.4f}. 전체W30G 학습점수는아니다.')
    fs=[s for s in a['fold_statistics'] if s['member']==tag];lines.append(f'- {tag} W30G DIAG fold RMSE 표준편차 {min(s["fold_sd"] for s in fs):.4f}~{max(s["fold_sd"] for s in fs):.4f}, paired delta표준편차 {min(s["paired_delta_sd"] for s in fs):.4f}~{max(s["paired_delta_sd"] for s in fs):.4f}.')
    for kind in ['level','shape']:
        ss=[s for s in v['segments'] if s['member']==tag and s['segment']=='level_shape'];p=[100*(s[f'candidate_{kind}_rmse']/s[f'baseline_{kind}_rmse']-1) for s in ss];lines.append(f'- {tag} DIAG {kind} RMSE 변화 {min(p):+.3f}~{max(p):+.3f}%.')
    for seg in ['F13','F47','early','late','hour00_05','hour06_17','hour18_23']:
        p=[s['delta_pct'] for s in v['segments'] if s['member']==tag and s['segment']==seg];lines.append(f'- {tag} {seg}: {min(p):+.3f}~{max(p):+.3f}%.')
gamma=[s['gamma'] for s in a['inner_and_outer_split_and_gamma']];lines+=['', f'I1의 fold별 gamma는 {min(gamma):.6f}~{max(gamma):.6f}. 계수는1미만축소와1초과증폭둘다허용했으며 학습결과를외부점수에맞춰재조정하지않았다. 내부모델은외부최종모델보다학습일이적어잔차계수의전이차이가생길수있다. 내부OOF계수최적화가외부개선을보장하지않음을이번결과가보여준다.', '', '## 최종 검산·재현·한계','', '- 검산 PASS: 모든 OOF 정답이 raw train_y와 동일·행중복없음, CSV math.fsum RMSE/독립 혼합식/20k5일블록bootstrap p/CI 동일. 전체24 seed×fold에서 원 CODEX 재학습과저장기준 최대차0.','- pipeline_audit PASS: 모든내부train/query와외부query 날짜집합±1buffer 독립 재구성·훈련subset검사·내부query합집합=외부train, cal_y 원시정답 일치. gamma분자/분모 math.fsum독립재계산·clip·추론식 재구성 일치.','- raw MASK 특징부터 첫 원DIAG fold seed726을 재학습해 A1/B1/C1/I1/physics 예측 최대차0. 모든fold 재학습 반복은하지않음. run.py는원시입력부터전체실험을실행하며캐시는기존성과와동일행확인한다.','- 새median/scaler/Ridge/트리는각외부/내부train에서만fit. 학습행은test입력NaN MASK, C1추가변환은원래인과특징의행내산술. 평가동시배치·미래입력·다른온실입력통계추가없음. 학습정답이잔차/계수학습에쓰이는것과평가정답누수는구별한다.','- 기존TF가중치의global입력rank는고정비교조건으로유지했고내부fold별재정의안함. BASE/PFN저장OOF재사용. CODEX726/727은샘플링이없어예측동일하므로실질독립시드증거2개로세지않는다. 전체혼합은BASE7/101·PFN1~8/17~24에서도검사했다.','- 동일CV반복사용한탐색·독립미사용홀드아웃/최종제출3시드모델/리더보드검증아님. 원기준불통과로전체W30G날씨GUARD추가채택검증안함. 반론: 저온B1국소개선으로교체가능한가? 사전전검증규칙과DIAG통계불통과라채택불가. 네안실패가모든추론식불가능성을증명하는가? 아니다.','- 실험과검산worker정상종료. test평가예측·제출파일·플랫폼업로드·EC최종잠금열람0. 큰결과 local/temp_pipeline_20261003_v1에보존,원자료/기존산출물수정0.','']
(H/'결과보고서_v1.md').write_text('\n'.join(lines),encoding='utf-8');print('\n'.join(lines[16:23]))
