"""Save the completed positive-only LOO diagnosis in shared handoff records."""
from pathlib import Path
import sys,json,re
H=Path(__file__).resolve().parent;ROOT=H.parents[3];sys.path.insert(0,str(ROOT/'집/코덱스/analysis/ec_highday_classifier_20261009_v1'));import runtime_v1,run_v1 as P
assert (H/'critique_final_v1.md').exists()
s=json.loads((H/'final_score_v1.json').read_text(encoding='utf8'));assert s['status']=='FULL_LOO';assert json.loads((H/'fresh_scalar_checks_v1.json').read_text(encoding='utf8'))['status']=='PASS'
x=s['paired_h15'];cat=ROOT/'공용/데이터_단서_카탈로그.md';text=cat.read_text(encoding='utf8');number=max(map(int,re.findall(r'\| 6\.(\d+) \|',text)))+1
summary=f"**2026-10-09 · 집 · 코덱스 고EC일LOOCV 진단 완료:** 사용자제안 고EC26일을한날24행씩holdout·train일반/고EC둘다. 같은73prefix+ET3seed/logit/prior·purge유지(일반일평가0). h15 기존DIAG{x['diag']['caught05']}/26→LOO{x['loo']['caught05']}/26탐지,놓침{x['loo']['missed05']},새탐지{x['gained']}·새놓침{x['lost']};.2보조탐지{x['loo']['caught02']}/26. 양성조건부Brier{x['diag']['conditional_positive_brier']:.6f}→{x['loo']['conditional_positive_brier']:.6f}/탐색block{x['blocks']} CI{x['delta_brier_ci95']}/p_worse{x['p_worse']:.5f}. LOOtrain296~303일/high18~22 vs해당DIAGhigh13~20(일반일도동시증가),새자료없음·표본수원인확정불가·오탐/전체효용미측정. source/purge/모든metric/paired/bootstrap독립PASS·3단계비평. 첫2fit뒤빈농장index dtype오류는v3정수집계수정만/fit·예측변경0. 소비40성능재점수0/새최종모델0/채택0/제출0. 카탈로그6.{number};own ec_highday_positive_loo_20261009_v1/report_v1.md."
entry=f"| 6.{number} | **고EC일26일 한날씩LOOCV: 양성탐지진단,전체구분효용미측정** (2026-10-09집코덱스/사용자제안·3단계비평) | "+summary+" | 집/코덱스/analysis/ec_highday_positive_loo_20261009_v1/{PLAN_v2.md,run_v3.py,registration_v1.json,continuation_registration_v1.json,final_score_v1.json,report_v1.md,critique_final_v1.md,fresh_scalar_checks_v1.json};집/코덱스/local/ec_highday_positive_loo_20261009_v1/final_paired_h15_v1.csv |"
assert 'ec_highday_positive_loo_20261009_v1/report_v1.md' not in text
with cat.open('a',encoding='utf8') as f:f.write('\n'+entry+'\n')
p=ROOT/'공용/HANDOFF.md';body=p.read_text(encoding='utf8');p.write_text('> '+summary+'\n\n'+body,encoding='utf8')
p=ROOT/'집/코덱스/작업일지/2026-10-09.md'
body='\n## 세션 7 — 고EC일 한 날씩 LOOCV 분류 진단\n\n### 읽은 것·계획\n\n사용자제안 고EC부분만LOOCV. predictive-modeling/검증·누수reference/skill-not-luck/analysis-before-answers/harsh-critic/analysis-verification 적용. 카탈로그6.469(독립분류기),6.471(클로드혼합기기각)확인,별도구분모델의동일설정검증배치만변경. 학습은일반일+고EC양class,검증만공개고EC26일24행씩. 소비40label값추가읽기0·공식test/이전대회자료0.\n\n### 실행·결과\n\n'+summary+'\n\nh0/8/15/23각26고EC일지표,3seed8383/1919/7171 모두보고. .5고정/.2사전민감도만. ROC/AP/precision/FPR/accuracy는양성only라보고안함. 시드선별/재균형/특징변경/학습파라미터튜닝0. 총26×4foldfit 완료,원모델final400재fit0. 실제train상수prior는day고EC비율. fold내imputer/logit/ET만fit,같은농장target±1/다른농장±3/잠금40±1포함purge.\n\n### 비평·보강·독립 재검산\n\n계획비평의실제DIAG10 baselineCSV해시누락을run_v2/PLAN_v2에서고정등록. 첫2fit예측48행은정상저장됐으나빈F47numpychoice배열의float승격으로bootstrap indexerror. run_v3에서concatindex.int64만수정/continuation등록추가,기존핀유지/fit재실행0/중간집계만재계산. 별도비평가가이수정과분할·targets·중간24metricgroups·paired/bootstrap검산PASS. 첫F13120/121두날1block의퇴화CI독립증거0 명시.\n\n최종공개high26/26분할/purge/source/targets/3seed/metric/paired/bootstrap독립검산과root stdlibcsv loopcount/mathfsum positiveBrier/means/새잡힘·새놓침 fresh_scalar_checks_v1.json PASS. 같은query의기존DIAGtrain은모든26LOOtrain의subset임을training_exposure_v1.json 확인. 진단결과좋고나쁨과무관하게현재결과로원인(표본부족/변수부족/모델설정)을분리하지않는다.\n\n### 다음·파일\n\n일반일의오탐률을새LOO에서확인하지않았고새홀드아웃없음. 새임계값/균형학습/새특징/EC회귀gate는별도사전설계후전체class검증이필요(현재미실행). 모델원본과타AI파일/프로세스수정0/새브랜치·커밋·제출0. own분석폴더PLAN_v1/v2,run_v1/v2/v3,bootstrap_repair_v1,registration/continuation,midpoint/final_score,report,training_exposure,fresh_scalarchecks,critic_* /critique_*;ownlocal/predictions26CSV+receipt 및final_paired_h15_v1.csv에결과저장. 세션종료sync_end는양AI작업끝난후사용자실행권장.\n'
with p.open('a',encoding='utf8') as f:f.write(body)
P.save(H/'session_record_v1.json',dict(catalogue='6.'+str(number),session=7,handoff_updated=True,submission=False));print('RECORDS_UPDATED','6.'+str(number))
