from world import *
import time
while not (HERE/'verification.json').exists():time.sleep(10)
j=json.loads((HERE/'result.json').read_text(encoding='utf-8'));v=json.loads((HERE/'verification.json').read_text(encoding='utf-8'));assert v['status']=='PASS';rs=j['summary'];score=pd.DataFrame(rs)
lines=['# 온도 계절 분담 TK1–TK3 결과','', '2026-10-03 집 코덱스. 사용자 요청서 직접 실행. 사전 main b730e80, 기존 W30G 비중·게이트 유지, 리더보드로 선택하지 않음. TK4는 별도 지시 전 생성하지 않음.','',f"TK2 판정: **{j['verdicts']['TK2_W30G']}**. BASE/CODEX 전체 계절 변경(TK3 비교) 판정: **{j['verdicts']['TK3_TC2_W30G']}**.",'','## TabPFN day→계절: 고정 W30G 전체 비교','', '|검증기|BASE 시드|PFN 문맥|원 RMSE|변경 RMSE|상대 변화|P(worse)|','|---|---:|---|---:|---:|---:|---:|']
for r in rs:
    if r['variant']=='TK2_W30G' and r['segment']=='all':lines.append(f"|{r['validator']}|{r['seed']}|{r['context']}|{r['baseline_rmse']:.6f}|{r['candidate_rmse']:.6f}|{r['delta_pct']:+.3f}%|{r.get('p_worse','—')}|")
lines+=['','PFN 체크포인트 V2·4estimators·2000행·float32 CUDA, 동일 표본과 모델 시드로 원본/계절 팔을 모두 재계산. 문맥1–8와17–24 각8개 평균. DIAG10/EXT10/EXT12 전체12칸 같은 개선 방향 및 DIAG20,000회 농장×5일 block bootstrap P(worse)<.025/18=0.001389, CI상단<0 요구. 작은 이득도 이 조건을 통과해야 채택 가능하다.','', '## PFN 단독과 후반','', '|범위|검증기|문맥|원 RMSE|계절 RMSE|변화|','|---|---|---|---:|---:|---:|']
for r in rs:
    if r['variant']=='TK2_PFN' and r['segment'] in ['all','late','F47_late']:lines.append(f"|{r['segment']}|{r['validator']}|{r['context']}|{r['baseline_rmse']:.6f}|{r['candidate_rmse']:.6f}|{r['delta_pct']:+.3f}%|")
lines+=['','## 평가형 EL1와 기존 검증의 차이','','EL1는 후반56정답일·1,344행을 농장별 기록순5일 묶음(12fold)으로 각각 제외하고 ±1일 버퍼를 둔다. 다른 농장 정답은 남긴다. 가까운 정답 날짜가 학습에 남는 결측일 예측 보강이며 기존DIAG10은 모든 날짜를10개fold로 분배한다. 평가60일의 독립 잠금 대신 사용할 수 없고 EL1 이득으로 기존 검증 실패를 덮지 않는다. 전체 BASE7/101/CODEX와 두 PFN문맥을 EL1에서도 새학습했다.','', '## 오차 지도와 독립 재현','','TK1의 기존W30G 후반 RMSE .793103, F13 .467192/F47 1.034496. F47 후반 하루수준SSE79.19%. 자세한 전후반·달력·밀폐 표는 [TK1_오차지도_v2.md](TK1_오차지도_v2.md), 초안v1은 밀폐BASE 숫자 오류가 있어 인용 금지.','','독립PAV와7회차원소스 재학습으로 클로드 TC1/TC2 예측 및 원PFN혼합 최대차1.0658e-14. 실제BASE day_hinge0개 감사. 자세한 원PFN 기준 재현은 [TK3_독립재현.md](TK3_독립재현.md). 본 표의TK3 비교는 재계산한PFN이고 클로드 원결과재현표와 구별한다.','', '## 검증과 한계','',f"최종 `verification.json`: {v['status']}. 원CSV라벨/독립math.fsum RMSE/42오차지도셀/혼합식/문맥학습subset/날짜분할/소스해시/20kbootstrap 반복 확인. 원TC1/TC2 예측 재현 최대차 {v['reproduction_maxdiff']:.3g}. 체크포인트·라이브러리·원자료/캐시 SHA256은 repro_metadata.json. 모델별 fold RMSE 표준편차는 model_scores.csv.",'','계절 변환 fit에는 해당fold 학습날씨만 전달하고 검증일에는 농장·기록일로 보간한다. MASK 피처재구성 후 원PFN FULL 대비학습행 최대차0 감사. 달력·밀폐 표지는 사후진단용이며 추론에 넣지 않음. 기존TF 전체 학습일 rank가중치 관행은 유지했고 fold지역 가중치 실험으로 해석하지 않음. 학습/검증오차 격차는 추가학습예측을 만들지 않아 측정하지 않음. CODEX726/727 실질동일이라 두독립시드 증거아님. 반복CV이며 온도독립잠금자료없음. 신뢰도: 수치재현 높음, 실전일반화 중간 이하.','', '반론: 후반이나 EL1만 좋아지면 대체할 수 있는가? 고정 규칙상 전체검증의 방향·신뢰구간이 우선이다. 이번 day 교체 실패로 다른 계절피처나 모든온도개선 불가능성을 주장할 수 없다. 단일변경실험이며 TC2+TK2 동시계절 변경 조합을 채택한 결과가 아니다.','', 'GPU실행 속도probe는 통계선택과 별도였다. 자동batch끄기는 수치동등조건실패, KV명시반복attention은 수치차0이나속도이득없어 모두적용하지 않았다. 원float32 worker사용. 통과후보가생기면 날씨그룹GUARD/CPU재현을 거쳐야 한다.']
(HERE/'TK_종합보고서_v1.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');print('FINAL REPORT WRITTEN')
